//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberMySql.java
//  @ Date : 2019-08-14
//  @ Author : 
//
//




public class MemberMySql {
}
