//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : management.java
//  @ Date : 2019-07-04
//  @ Author : 
//
//




public class management {
	public String name;
	public int age;
	public String sex;
	public String address;
	public int phone;
	public String E_mail_address;
	public void printname() {
	
	}
	
	public void printage() {
	
	}
	
	public void printsex() {
	
	}
	
	public void printaddress() {
	
	}
	
	public int printphone() {
		return 0;
	}
	
	
	public void printE_mail_address() {
	
	}
}
