package MemberManager;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberMySql.java
//  @ Date : 2019-08-14
//  @ Author : 
//
//




public class MemberMySql {

	public MemberMySql(Login_PL login_PL) {
		
	}
	public static void main(String[] args) {
		System.out.println("MySql");
	}
}
