package MemberManager;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MemberOracle.java
//  @ Date : 2019-08-14
//  @ Author : 
//
//




public class MemberOracle {

	public MemberOracle(Login_PL login_PL) {
		// TODO Auto-generated constructor stub
	}
	public static void main(String[] args) {
		System.out.println("Oracle");
	}
}
